### ISSUE TITLE
Save button on schemaeditor toolbar does nothing

### ISSUE THREAD

**Issue by eflumerf** [DUNE-DAQ/dbe#34]
I've noticed that clicking the "Save" icon on the toolbar doesn't ever seem to do anything, but File -> Save does, and trying to exit will give me a confirmation dialog asking to save even if I haven't made any changes since the last save.

**Comment by gcrone** [comment]
The "Save" icon on the toolbar is for saving schema views not the schema files themselves. If you hover the mouse pointer over it the tooltip "Save view" pops up.

The prompt for saving of files when nothing has changed is a nuisance and part of the cmoplaint in issue https://github.com/DUNE-DAQ/dbe/issues/27

**Comment by eflumerf** [comment]
Should there be a "Save Schema" icon on the taskbar, with some "view vs. schema" iconography to distinguish them (e.g. magnifying glass for view, scroll for schema)

**Comment by gcrone** [comment]
Maybe, I'm not good at iconography but have made some updates in PR #32 that attempt to address this
